---
title: "Статистический отчет"
subtitle: "Биостатистика 2023"
author: "Nadja Lukashevich"
date: "`r Sys.Date()`"
output: 
  word_document:
    toc: yes
    toc_depth: 3
toc-title: "Оглавление"

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require('readr')
require('dplyr')
require('flextable')
require('tidyr')
```

# Обзор Данных

```{r, include=FALSE}
dataset <- readr::read_delim(file = "data/raw/data_tsv.tsv", delim = '\t')
```

```{r, results='asis', echo=FALSE}
basic_stats <- summary(dataset)
dataset_size <- dim(dataset)
var_names <- names(dataset)

numerical_vars <- names(dataset)[sapply(dataset, is.numeric)]
categorical_vars <- setdiff(var_names, numerical_vars)

cat(paste0("Датасет состоит из ", dataset_size[1], " строк и ", dataset_size[2], " колонок.\n",
           "Переменные в датасете: ", paste(var_names, collapse = ", "), ".\n", 
           "Из них качественных ",length(categorical_vars), ": ", paste(categorical_vars, collapse = ", "), ".\n",
           "А количественных ",length(numerical_vars), ": ", paste(numerical_vars, collapse = ", "), ".\n"))

```

## Статистика по качественным переменным
### Общая статистика
```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}
grouped_data <- dataset %>% 
  gather(key = "Переменная", value = "Значение", Группа, Пол, `Группа крови`) %>% 
  group_by(Переменная, Значение) %>% 
  summarise(
    'Количество субъектов' = n(),
    'Количество (есть данные)' = sum(!is.na(Значение)),
    'Количество пропущенных значений' = sum(is.na(Значение))
  )

sum_data <- grouped_data %>% 
  group_by(Переменная) %>% 
  summarise(
    'Количество субъектов' = sum(`Количество субъектов`),
    'Количество (есть данные)' = sum(`Количество (есть данные)`),
    'Количество пропущенных значений' = sum(`Количество пропущенных значений`)
  ) %>% 
  mutate(Значение = "Итого")

final_data <- bind_rows(grouped_data, sum_data) %>% 
  arrange(Переменная)

ft <- final_data %>% 
  flextable() %>% 
  merge_v(j = ~Переменная) %>% 
  theme_box()

ft
```
### Пересечение группы и других качественных переменных

```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}
grouped_gender_group <- dataset %>% 
  group_by(Группа, Пол) %>% 
  summarise(
    'Количество субъектов' = n(),
    'Количество (есть данные)' = sum(!is.na(Пол)),
    'Количество пропущенных значений' = sum(is.na(Пол))
  )

grouped_group_blood <- dataset %>% 
  group_by(Группа, `Группа крови`) %>% 
  summarise(
    'Количество субъектов' = n(),
    'Количество (есть данные)' = sum(!is.na(`Группа крови`)),
    'Количество пропущенных значений' = sum(is.na(`Группа крови`))
  )
```
```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}
ft <- grouped_gender_group %>% 
  arrange(Группа) %>% 
  flextable() %>% 
  merge_v(j = ~Группа) %>% 
  theme_box()
ft
```
```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}
ft <- grouped_group_blood %>% 
  arrange(Группа) %>% 
  flextable() %>% 
  merge_v(j = ~Группа) %>% 
  theme_box()
ft
```
# Статистика по количественным переменным
```{r, echo=FALSE,warning=FALSE,message=FALSE,error=FALSE}
numerical_vars <- names(dataset)[sapply(dataset, is.numeric)]
numerical_vars <- setdiff(numerical_vars, c("Возраст", "Рост"))
vars_E1 <- sort(grep("_E1$", numerical_vars, value = TRUE))
vars_E2 <- sort(grep("_E2$", numerical_vars, value = TRUE))
numerical_vars <- c("Возраст", "Рост", vars_E1, vars_E2)

calculate_stats <- function(data, var) {
  stats_long <- data %>% 
    group_by(Группа) %>% 
    summarise(
      n = n(),
      `Количество (есть данные)` = sum(!is.na(!!sym(var))),
      `Нет данных` = sum(is.na(!!sym(var))),
      `Ср.знач` = mean(!!sym(var), na.rm = TRUE),
      `Ст. отклон` = sd(!!sym(var), na.rm = TRUE),
      `95% ДИ для среднего` = qt(0.975, df=n()-1)*sd(!!sym(var), na.rm = TRUE)/sqrt(n()),
      `мин-макс` = paste(min(!!sym(var), na.rm = TRUE), "-", max(!!sym(var), na.rm = TRUE)),
      `Медиана` = median(!!sym(var), na.rm = TRUE),
      `Q1-Q3` = paste(quantile(!!sym(var), 0.25, na.rm = TRUE), "-", quantile(!!sym(var), 0.75, na.rm = TRUE))
    ) %>% 
    mutate(across(everything(), as.character)) %>% 
    pivot_longer(-Группа, names_to = "Статистика", values_to = "Значение") %>% 
    mutate(Переменная = var)
  
  return(stats_long)
}

list_of_stats <- lapply(numerical_vars, function(var) calculate_stats(dataset, var))
final_data <- bind_rows(list_of_stats)%>% select(Переменная,Группа, Статистика, Значение)

ft_numerical <- final_data %>% 
  flextable() %>% 
  merge_v(j = ~Группа) %>% 
  merge_v(j = ~Переменная) %>% 
  theme_box()


ft_numerical
```


